### ISSUE TITLE
React-Table.css parse error

### ISSUE THREAD

**Issue by moriyente** [react-tools/react-table#659]
Dear , 
  I created new react js project and i imported this module. It was work any problem. But when I imported in my project  I get error. Could you help me please ? 
 
Here below ,
ERROR in ./~/react-table/react-table.css
Module parse failed: C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\react-table\react-table.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:2222:15)
    at Parser.pp.unexpected (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:604:10)
    at Parser.pp$3.parseExprAtom (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1823:14)
    at Parser.pp$3.parseExprSubscripts (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1716:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1693:19)
    at Parser.pp$3.parseExprOps (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1638:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1621:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1598:21)
    at Parser.pp$3.parseExpression (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:1574:21)
    at Parser.pp$1.parseStatement (C:\Users\IDARA\Desktop\VsCode\VisionForm_Grid\node_modules\webpack\node_modules\acorn\dist\acorn.js:728:49)

**Comment by gary-menzel** [comment]
This looks environment related to me. This question is better asked on the #react-table Slack channel (where a wider range of users may have experienced this problem and have a solution for it).  You can find a badge at the top of the README in the doco.  The github issues are reserved for bugs or feature requests with the code.
